// <auto-generated> by WinCBridgeGen — do not edit by hand.
// Regenerate with:  swift package generate-csharp-bridge
// Source of truth: the @WinC functions in Sources/SwiftXStateWinBridge.
using System;
using System.Runtime.InteropServices;

namespace SwiftXStateWinBridgeInterop
{
    public static class SwiftXStateWinBridge
    {
        private const string DllName = "SwiftXStateWinBridge.dll";

        // Free a C string that Swift allocated (Universal C Runtime `free`).
        [DllImport("ucrtbase.dll", EntryPoint = "free", CallingConvention = CallingConvention.Cdecl)]
        private static extern void FreeCString(IntPtr ptr);

        // Read a UTF-8 C string from Swift and free it. Swift strings are UTF-8.
        private static string ConsumeCString(IntPtr ptr)
        {
            if (ptr == IntPtr.Zero) return string.Empty;
            try { return Marshal.PtrToStringUTF8(ptr) ?? string.Empty; }
            finally { FreeCString(ptr); }
        }

        // Live inspection callback: one JSON document per event. Keep your delegate instance alive for
        // as long as it's registered, or the GC may collect it. The json string is a copy you own.
        [UnmanagedFunctionPointer(CallingConvention.Cdecl)]
        public delegate void SnapshotCallback([MarshalAs(UnmanagedType.LPUTF8Str)] string json);

        // --- ActorContextJSON ---
        [DllImport(DllName, EntryPoint = "ActorContextJSON", CallingConvention = CallingConvention.Cdecl)]
        private static extern IntPtr NativeActorContextJSON(long handle);

        public static string ActorContextJSON(long handle) => ConsumeCString(NativeActorContextJSON(handle));

        // --- ActorCreate ---
        [DllImport(DllName, EntryPoint = "ActorCreate", CallingConvention = CallingConvention.Cdecl)]
        private static extern long NativeActorCreate([MarshalAs(UnmanagedType.LPUTF8Str)] string name);

        public static long ActorCreate(string name) => NativeActorCreate(name);

        // --- ActorEvents ---
        [DllImport(DllName, EntryPoint = "ActorEvents", CallingConvention = CallingConvention.Cdecl)]
        private static extern IntPtr NativeActorEvents(long handle);

        public static string ActorEvents(long handle) => ConsumeCString(NativeActorEvents(handle));

        // --- ActorRelease ---
        [DllImport(DllName, EntryPoint = "ActorRelease", CallingConvention = CallingConvention.Cdecl)]
        private static extern void NativeActorRelease(long handle);

        public static void ActorRelease(long handle) => NativeActorRelease(handle);

        // --- ActorSend ---
        [DllImport(DllName, EntryPoint = "ActorSend", CallingConvention = CallingConvention.Cdecl)]
        private static extern int NativeActorSend(long handle, [MarshalAs(UnmanagedType.LPUTF8Str)] string @event);

        public static int ActorSend(long handle, string @event) => NativeActorSend(handle, @event);

        // --- ActorSetSnapshotCallback ---
        [DllImport(DllName, EntryPoint = "ActorSetSnapshotCallback", CallingConvention = CallingConvention.Cdecl)]
        private static extern void NativeActorSetSnapshotCallback(long handle, SnapshotCallback callback);

        public static void ActorSetSnapshotCallback(long handle, SnapshotCallback callback) => NativeActorSetSnapshotCallback(handle, callback);

        // --- ActorState ---
        [DllImport(DllName, EntryPoint = "ActorState", CallingConvention = CallingConvention.Cdecl)]
        private static extern IntPtr NativeActorState(long handle);

        public static string ActorState(long handle) => ConsumeCString(NativeActorState(handle));

        // --- AddNumbers ---
        [DllImport(DllName, EntryPoint = "AddNumbers", CallingConvention = CallingConvention.Cdecl)]
        private static extern int NativeAddNumbers(int a, int b);

        public static int AddNumbers(int a, int b) => NativeAddNumbers(a, b);

        // --- MachineCreate ---
        [DllImport(DllName, EntryPoint = "MachineCreate", CallingConvention = CallingConvention.Cdecl)]
        private static extern long NativeMachineCreate([MarshalAs(UnmanagedType.LPUTF8Str)] string definitionJSON);

        public static long MachineCreate(string definitionJSON) => NativeMachineCreate(definitionJSON);

        // --- MachineEvents ---
        [DllImport(DllName, EntryPoint = "MachineEvents", CallingConvention = CallingConvention.Cdecl)]
        private static extern IntPtr NativeMachineEvents(long handle);

        public static string MachineEvents(long handle) => ConsumeCString(NativeMachineEvents(handle));

        // --- MachineList ---
        [DllImport(DllName, EntryPoint = "MachineList", CallingConvention = CallingConvention.Cdecl)]
        private static extern IntPtr NativeMachineList();

        public static string MachineList() => ConsumeCString(NativeMachineList());

        // --- MachineMatches ---
        [DllImport(DllName, EntryPoint = "MachineMatches", CallingConvention = CallingConvention.Cdecl)]
        private static extern int NativeMachineMatches(long handle, [MarshalAs(UnmanagedType.LPUTF8Str)] string statePath);

        public static int MachineMatches(long handle, string statePath) => NativeMachineMatches(handle, statePath);

        // --- MachineRelease ---
        [DllImport(DllName, EntryPoint = "MachineRelease", CallingConvention = CallingConvention.Cdecl)]
        private static extern void NativeMachineRelease(long handle);

        public static void MachineRelease(long handle) => NativeMachineRelease(handle);

        // --- MachineReset ---
        [DllImport(DllName, EntryPoint = "MachineReset", CallingConvention = CallingConvention.Cdecl)]
        private static extern void NativeMachineReset(long handle);

        public static void MachineReset(long handle) => NativeMachineReset(handle);

        // --- MachineSend ---
        [DllImport(DllName, EntryPoint = "MachineSend", CallingConvention = CallingConvention.Cdecl)]
        private static extern int NativeMachineSend(long handle, [MarshalAs(UnmanagedType.LPUTF8Str)] string @event);

        public static int MachineSend(long handle, string @event) => NativeMachineSend(handle, @event);

        // --- MachineSetStateCallback ---
        [DllImport(DllName, EntryPoint = "MachineSetStateCallback", CallingConvention = CallingConvention.Cdecl)]
        private static extern void NativeMachineSetStateCallback(long handle, SnapshotCallback callback);

        public static void MachineSetStateCallback(long handle, SnapshotCallback callback) => NativeMachineSetStateCallback(handle, callback);

        // --- MachineState ---
        [DllImport(DllName, EntryPoint = "MachineState", CallingConvention = CallingConvention.Cdecl)]
        private static extern IntPtr NativeMachineState(long handle);

        public static string MachineState(long handle) => ConsumeCString(NativeMachineState(handle));

        // --- SampleDefinitionJSON ---
        [DllImport(DllName, EntryPoint = "SampleDefinitionJSON", CallingConvention = CallingConvention.Cdecl)]
        private static extern IntPtr NativeSampleDefinitionJSON();

        public static string SampleDefinitionJSON() => ConsumeCString(NativeSampleDefinitionJSON());

        // --- SwiftXStateVersion ---
        [DllImport(DllName, EntryPoint = "SwiftXStateVersion", CallingConvention = CallingConvention.Cdecl)]
        private static extern IntPtr NativeSwiftXStateVersion();

        public static string SwiftXStateVersion() => ConsumeCString(NativeSwiftXStateVersion());
    }
}
