import Foundation

/// A compile-time-checked state reference — the raw value is the dot-path from the machine root
/// (`"red.wait"`). Conformers are normally generated by `@MachineStates`, so the set of cases can
/// never drift from the declared states.
///
/// Targets are emitted as `#`-absolute ids, which resolve no matter where the transition is
/// declared — sidestepping relative-target ambiguity.
public protocol StateName: RawRepresentable, Sendable where RawValue == String {}

public extension StateName {
    /// The absolute transition target string for this state (e.g. `"#red.wait"`).
    var target: String { "#\(rawValue)" }
}

// MARK: - Generator

/// Generates a `StateName` enum (named by the argument) from the `states:` of the `MachineConfig`
/// this is attached to. Keeps state-name references compile-checked, autocompleted, and
/// rename-safe, with zero hand-maintained boilerplate.
///
/// ```swift
/// @MachineStates("AppState")
/// let config = MachineConfig(id: "app", initial: "idle", states: [
///     "idle":   StateNodeConfig(on: transitions(on(Go.self, to: AppState.running))),
///     "running": StateNodeConfig(states: ["fast": StateNodeConfig(), "slow": StateNodeConfig()]),
/// ])
/// // generates: enum AppState: String, StateName { case idle; case running; case runningFast = "running.fast"; … }
/// ```
@attached(peer, names: arbitrary)
public macro MachineStates(_ name: String) =
    #externalMacro(module: "SwiftXStateMacros", type: "MachineStatesMacro")

// MARK: - Typed targets (Tier 2)

public extension TransitionInput {
    /// Type-safe transition target from a generated `StateName`.
    static func to<S: StateName>(_ state: S) -> TransitionInput<Context> {
        .target(state.target)
    }
}

/// Typed `on(...)` transition with a compile-checked `StateName` target.
public func on<Context: Sendable, E: StateEvent, S: StateName>(
    _ event: E.Type,
    to state: S,
    reenter: Bool? = nil,
    guard guardRef: GuardRef<Context>? = nil,
    actions: [ActionRef<Context>] = []
) -> EventTransition<Context> {
    on(event, target: state.target, reenter: reenter, guard: guardRef, actions: actions)
}
